/**
 * Host dictionary. A host found here costs an escape-coded index (bits.js)
 * instead of its full text — 3 bits for the most-shared handful, 11 for the
 * rest of the table, open-ended past it.
 *
 * ORDERED BY MEASURED USE, then APPEND-ONLY. An entry's position IS its
 * wire encoding, so reordering or removing one silently repoints every link
 * already shared. Add to the end, never anywhere else; the escape-coded
 * index has no cap. (This order was set once, from the corpus, while the
 * format was still beta; from 1.0 on it never moves again.)
 *
 * @type {readonly string[]}
 */
export const HOSTS = Object.freeze([
  "youtube.com","twitter.com","github.com","x.com","archive.org",
  "medium.com","doi.org","npmjs.com","pypi.org","commons.wikimedia.org",
  "en.wikipedia.org","upload.wikimedia.org","open.spotify.com","goodreads.com","discogs.com",
  "mastodon.social","rottentomatoes.com","facebook.com","instagram.com","flickr.com",
  "imdb.com","linkedin.com","soundcloud.com","nytimes.com","news.google.com",
  "pubeurope.com","theguardian.com","i.imgur.com","techcrunch.com","arstechnica.com",
  "flipboard.com","reddit.com","arxiv.org","bloomberg.com","news.ycombinator.com",
  "reuters.com","wsj.com","imgur.com","google.com","www.google.com",
  "bbc.com","completewhois.com","theregister.com","bbc.co.uk","letterboxd.com",
  "tools.wikimedia.de","theverge.com","nature.com","kickstarter.com","tiktok.com",
  "catalogueoflife.org","wired.com","phys.org","fed.brid.gy","news.bbc.co.uk",
  "washingtonpost.com","ft.com","cnbc.com","old.reddit.com","theatlantic.com",
  "cnn.com","economist.com","europesays.com","businessinsider.com","channels.im",
  "britannica.com","wikisky.org","bsky.app","npr.org","apnews.com",
  "forbes.com","amazon.com","phoronix.com","twitch.tv","engadget.com",
  "tomshardware.com","gizmodo.com","lemmy.ml","patreon.com","technologyreview.com",
  "spectrum.ieee.org","newyorker.com","theconversation.com","venturebeat.com","apps.apple.com",
  "readwriteweb.com","macrumors.com","web.archive.org","zdnet.com","ssd.jpl.nasa.gov",
  "gist.github.com","toolserver.org","mashable.com","mstdn.social","misskey.io",
  "scientificamerican.com","huggingface.co","quora.com","thenextweb.com","fortune.com",
  "axios.com","rss-parrot.net","abc.net.au","cbc.ca","science.org",
  "finance.yahoo.com","chromewebstore.google.com","books.google.com","latimes.com","guardian.co.uk",
  "stackoverflow.com","wakoka.com","lwn.net","sciencedirect.com","hackaday.com",
  "bleepingcomputer.com","medicalxpress.com","fastcompany.com","telegraph.co.uk","vive.im",
  "code.google.com","mastodon.world","newscientist.com","electrek.co","substack.com",
  "google.co.uk","online.wsj.com","threads.com","ncbi.nlm.nih.gov","eff.org",
  "nbcnews.com","nautil.us","sciencedaily.com","msn.com","slate.com",
  "newsbeep.org","cbsnews.com","thenewstack.io","techdirt.com","theregister.co.uk",
  "mastodon.online","politico.com","techxplore.com","9to5mac.com","lesswrong.com",
  "independent.co.uk","docs.google.com","time.com","sfgate.com","mas.to",
  "groups.google.com","mdpi.com","pixelfed.social","vox.com","torrentfreak.com",
  "uk.linkedin.com","simbad.u-strasbg.fr","bsky.brid.gy","secure.wikimedia.org","aws.amazon.com",
  "youtu.be","edition.cnn.com","gigaom.com","in.gr","nasa.gov",
  "uk.youtube.com","securityweek.com","vimeo.com","smithsonianmag.com","masto.ai",
  "blog.cloudflare.com","ethnologue.com","who.int","whc.unesco.org","sciencealert.com",
  "us.imdb.com","lemmy.world","infoq.com","recensement.insee.fr","microsoft.com",
  "apple.com","lema.rae.es","qz.com","wordreference.com","livescience.com",
  "pcmag.com","quantamagazine.org","i.redd.it","infosec.exchange","chessgames.com",
  "devblogs.microsoft.com","bit.ly","webcitation.org","vice.com","usatoday.com",
  "space.com","dm.mikrobit.pl","dl.acm.org","appleinsider.com","news.mit.edu",
  "allmusic.com","macobserver.com","kulturarvsdata.se","blog.google","maps.google.com",
  "itunes.apple.com","gutenberg.org","zenodo.org","pbs.org","popsci.com",
  "daringfireball.net","nypost.com","networkworld.com","billboard.com","scitechdaily.com",
  "thehill.com","newatlas.com","openai.com","scmp.com","news.cnet.com",
  "johndcook.com","aeon.co","aljazeera.com","bots.krohsnest.com","simonwillison.net",
  "dailymail.co.uk","neowin.net","marginalrevolution.com","nedwww.ipac.caltech.edu","play.google.com",
  "heise.de","inc.com","github.blog","404media.co","de.wikipedia.org",
  "fifa.com","hbr.org","newsweek.com","coindesk.com","techradar.com",
  "nextplatform.com","ign.fr","store.steampowered.com","plus.google.com","seds.org",
  "ol2ol.com","kolektiva.social","chrome.google.com","w3.org","in.linkedin.com",
  "mastodon.uno","money.cnn.com","politico.eu","huffingtonpost.com","techinasia.com",
  "slideshare.net","cacm.acm.org","restofworld.org","pcgamer.com","blogs.wsj.com",
  "theater.im","pnas.org","rsssf.com","japantimes.co.jp","computerworld.com",
  "itworld.com","variety.com","universeodon.com","atlasobscura.com","popularmechanics.com",
  "developer.apple.com","meta.wikimedia.org","thedrive.com","dw.com","pcworld.com",
  "abcnews.go.com","news.sky.com","businessweek.com","schneier.com","papers.ssrn.com",
  "cnet.com","euronews.com","hachyderm.io","bigthink.com","english.elpais.com",
  "reason.com","nobelprize.org","uefa.com","blogs.forbes.com","propublica.org",
  "delta-intkey.com","rollingstone.com","dnsstuff.com","pluralistic.net","piaille.fr",
  "gnu.org","thetimes.com","theintercept.com","indiehackers.com","link.springer.com",
  "universetoday.com","motherboard.vice.com","news.yahoo.com","hollywoodreporter.com","bots.fedi.cr",
  "newadvent.org","kotaku.com","farm4.static.flickr.com","cristin.no","spacenews.com",
  "nymag.com","cell.com","xcancel.com","cloud.google.com","fallingrain.com",
  "anthropic.com","onlinelibrary.wiley.com","webcache.googleusercontent.com","mathworld.wolfram.com","codeberg.org",
  "spin.atomicobject.com","wikipedia.org","smh.com.au","justice.gov","es.wiktionary.org",
  "mastodon.themetaldog.net","pmc.ncbi.nlm.nih.gov","sourceforge.net","boingboing.net","sports-reference.com",
  "ted.com","geocities.com","sciencemag.org","ani.social","pastebin.com",
  "paulgraham.com","tff.org","quickfacts.census.gov","myspace.com","krebsonsecurity.com",
  "spiegel.de","anandtech.com","sfchronicle.com","extremetech.com","utcc.utoronto.ca",
  "yahoo.com","buttondown.com","culture.gouv.fr","socket.dev","kathimerini.gr",
  "blogs.msdn.com","google.pl","androidauthority.com","marketwatch.com","avc.com",
  "developer.mozilla.org","world.hey.com","singularityhub.com","dx.doi.org","researchgate.net",
  "gitlab.com","lemonde.fr","france24.com","drive.google.com","rte.ie",
  "pubmed.ncbi.nlm.nih.gov","t.co","m.youtube.com","asahi.com","learn.microsoft.com",
  "jstor.org","vercel.com","chatgpt.com","espn.com","crates.io",
  "scholar.google.com","bitbucket.org","figma.com","elpais.com","claude.ai",
  "codepen.io","dropbox.com","python.org","nodejs.org","kaggle.com",
  "podcasts.apple.com","stripe.com","notion.so","developer.android.com","digitalocean.com",
  "docker.com","observablehq.com","t.me","fly.io","colab.research.google.com",
  "go.dev","etsy.com","jsfiddle.net","straitstimes.com","mail.google.com",
  "dribbble.com","standard.co.uk","tumblr.com","indeed.com","airbnb.com",
  "raw.githubusercontent.com","acm.org","cloudflare.com","discord.com","khanacademy.org",
  "golang.org","weather.com","itch.io","newegg.com","spotify.com",
  "corriere.it","glassdoor.com","itv.com","netlify.com","kubernetes.io",
  "netflix.com","udemy.com","yelp.com","threads.net","chess.com",
  "hub.docker.com","weibo.com","dailymotion.com","steamcommunity.com","ebay.com",
  "paypal.com","ikea.com","slack.com","zillow.com","hulu.com",
  "heroku.com","coursera.org","discord.gg","replit.com","pbs.twimg.com",
  "behance.net","render.com","wordpress.com","ieee.org","bestbuy.com",
  "walmart.com","edx.org","telegram.me","music.apple.com","whatsapp.com",
  "vk.com","springer.com","unsplash.com","homedepot.com","postimg.cc",
  "codesandbox.io","pinterest.com","tripadvisor.com","i.ibb.co","snapchat.com",
  "lowes.com","calendar.google.com","duolingo.com","rakuten.co.jp","target.com",
  "sky.com","preview.redd.it","zoom.us","booking.com","alibaba.com",
  "rust-lang.org","blogspot.com","otto.de","gofundme.com","strava.com",
  "live.staticflickr.com","office.com","taobao.com","costco.com","xiaohongshu.com",
  "argos.co.uk","asos.com","tesco.com","johnlewis.com","i.pinimg.com",
  "azure.com","outlook.com","wa.me","ytimg.com","ok.ru",
  "aliexpress.com","line.me","temu.com","shein.com","primevideo.com",
  "disneyplus.com","jd.com","mercadolibre.com","expedia.com","wayfair.com",
  "macys.com","nordstrom.com","chewy.com","sephora.com","carrefour.fr",
  "zalando.co.uk","console.aws.amazon.com","media.giphy.com","meet.google.com","cdn.discordapp.com",
  "images.unsplash.com","media.tenor.com",
]);

/** @type {ReadonlyMap<string, number>} */
export const HOST_INDEX = new Map(HOSTS.map((h, i) => [h, i]));
